version: "3.8"

services:

  mariadb:
    image: mariadb:latest
    volumes:
       - data-maria:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: domestique
      MYSQL_USER: root

  serveur:
    build: serveur_fastapi/
    container_name: taches
    ports:
      - 8080:8500
    depends_on:
      - mariadb
    
  mqtt:
    image: eclipse-mosquitto:2
    volumes:
      - ./mqtt/config/:/mosquitto/config/:ro
      - ./mqtt/log/:/mosquitto/log/
      - data-mqtt:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001


volumes:
  data-maria:
  data-mqtt: